"""initial schema

Revision ID: fc64113227e5
Revises:
Create Date: 2026-08-29 15:19:16.848453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc64113227e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('audit_event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=20), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('audit_event_id')
    )
    op.create_table('models',
    sa.Column('model_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('provider_family', sa.String(length=150), nullable=True),
    sa.Column('runtime', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('tools',
    sa.Column('tool_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('tool_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sensitivity_class', sa.String(length=30), server_default=sa.text("'confidential'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('knowledge_bases',
    sa.Column('knowledge_base_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_base_id')
    )
    op.create_table('model_versions',
    sa.Column('model_version_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('weights_path', sa.Text(), nullable=False),
    sa.Column('quantization', sa.String(length=50), nullable=True),
    sa.Column('vram_required_gb', sa.Numeric(), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_version_id'),
    sa.UniqueConstraint('model_id', 'version', name='model_versions_model_id_version_key')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('files',
    sa.Column('file_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('sensitivity_class', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('model_capabilities',
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('capability', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_version_id', 'capability')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('sensitivity_class', sa.String(length=30), server_default=sa.text("'confidential'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('approvals',
    sa.Column('approval_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('requested_from', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('decided_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['requested_from'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_table('deliverables',
    sa.Column('deliverable_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('format', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('approval_state', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deliverable_id')
    )
    op.create_table('documents',
    sa.Column('document_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.knowledge_base_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('model_calls',
    sa.Column('model_call_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('model_version_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.model_version_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_call_id')
    )
    op.create_table('task_files',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), server_default=sa.text("'input'"), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'file_id')
    )
    op.create_table('task_steps',
    sa.Column('step_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('step_id'),
    sa.UniqueConstraint('task_id', 'step_no', name='task_steps_task_id_step_no_key')
    )
    op.create_table('tool_calls',
    sa.Column('tool_call_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=80), nullable=False),
    sa.Column('args_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.tool_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('region_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='document_chunks_document_id_chunk_index_key')
    )
    op.create_table('evidence_records',
    sa.Column('evidence_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('model_call_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('validation_status', sa.String(length=30), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['model_call_id'], ['model_calls.model_call_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence_records')
    op.drop_table('document_chunks')
    op.drop_table('tool_calls')
    op.drop_table('task_steps')
    op.drop_table('task_files')
    op.drop_table('model_calls')
    op.drop_table('documents')
    op.drop_table('deliverables')
    op.drop_table('approvals')
    op.drop_table('tasks')
    op.drop_table('model_capabilities')
    op.drop_table('files')
    op.drop_table('projects')
    op.drop_table('model_versions')
    op.drop_table('knowledge_bases')
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_table('tools')
    op.drop_table('models')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
